# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('server', '服务器'), ('slb', '负载均衡'), ('rds', '阿里云rds'), ('other', '阿里云其他资产'), ('company', '公司资产')], default='server', max_length=64, verbose_name='资产类型')),
                ('region', models.CharField(choices=[('cn-qingdao', '华北1'), ('cn-beijing', '华北2'), ('cn-zhangjiakou', '华北3'), ('cn-huhehaote', '华北5'), ('cn-hangzhou', '华东1'), ('cn-shanghai', '华东2'), ('cn-shenzhen', '华南1'), ('company', '公司')], default='cn-shanghai', max_length=64, verbose_name='所属地域')),
                ('instance_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='实例ID')),
                ('instance_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='实例类型')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='资产名称')),
                ('status', models.CharField(choices=[('running', '在线'), ('stop', '下线'), ('unknow', '未知')], default='running', max_length=16, verbose_name='资产状态')),
                ('create_day', models.DateField(blank=True, null=True, verbose_name='创建日期')),
                ('expire_day', models.DateField(blank=True, null=True, verbose_name='过期日期')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '资产总表',
                'verbose_name_plural': '资产总表',
                'ordering': ['-create_day'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(choices=[('auto', '自动添加'), ('manual', '手工录入')], default='auto', max_length=16, verbose_name='添加方式')),
                ('in_ipaddr', models.CharField(blank=True, max_length=32, null=True, verbose_name='内网ip')),
                ('ou_ipaddr', models.CharField(blank=True, max_length=32, null=True, verbose_name='外网ip')),
                ('os_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='操作系统类型')),
                ('os_info', models.CharField(blank=True, max_length=16, null=True, verbose_name='操作系统信息')),
                ('cpu_info', models.CharField(blank=True, max_length=16, null=True, verbose_name='cpu信息')),
                ('memory_info', models.CharField(blank=True, max_length=16, null=True, verbose_name='内存信息')),
                ('business_unit', models.CharField(blank=True, max_length=128, null=True, verbose_name='服务器用途')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
            ],
            options={
                'verbose_name': '服务器资产表',
                'verbose_name_plural': '服务器资产表',
            },
        ),
    ]
