# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-13 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='show_status',
            field=models.IntegerField(choices=[(1, '确认'), (0, '待确认')], default=0, verbose_name='确认状态'),
        ),
        migrations.AlterField(
            model_name='server',
            name='created_by',
            field=models.CharField(choices=[('auto', '自动'), ('manual', '手工')], default='auto', max_length=16, verbose_name='添加方式'),
        ),
    ]
