# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-13 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180513_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='show_status',
            field=models.IntegerField(choices=[(1, '确认'), (0, '待确认'), (2, '删除')], default=0, verbose_name='确认状态'),
        ),
    ]
