# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 22:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=2)),
                ('group', models.CharField(default='', max_length=64)),
                ('createtime', models.DateField()),
                ('logintime', models.DateField(default='1970-01-01')),
                ('validkey', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=0)),
                ('avatar', models.CharField(default='', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
